name: crypto_trader
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  bloc: ^8.1.2
  image_picker: ^1.0.4
  hive: ^2.2.3
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_storage: ^11.5.2
  go_router: ^12.1.1
  hive_flutter: ^1.1.0
  http: ^1.1.0
  chart_sparkline: ^1.0.14
  dio: ^5.4.0
  flutter_spinkit: ^5.2.0
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^16.2.0
  fl_chart: ^0.65.0
  intl_phone_field: ^3.2.0
  flutter_libphonenumber: ^2.2.1
  path_provider: ^2.1.1
  flutter_native_image: ^0.0.6
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  fluttertoast: ^8.2.4
  flutter_localization: ^0.1.14
  local_auth: ^2.1.7
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.jpg"

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
  # example:
  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu.ttf
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
